Repository kostant/kmept_922-3, pull requests merged in 2024-12, with the labels that each got.

#1 addNewButton
  .idea/deploymentTargetDropDown.xml
  .idea/kotlinc.xml
  app/src/main/res/layout/activity_main.xml
Labels: good first issue, sosal?

#3 add new button "Влад Поляков"
  app/src/main/res/layout/activity_main.xml
Labels: enhancement, good first issue

#5 change button rinviu
  app/src/main/res/layout/activity_main.xml
Labels: enhancement, da!

#6 orlov button
  app/src/main/res/layout/activity_main.xml
Labels: bug, 148..8

#7 added button
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#2 added empty button
  app/src/main/res/layout/activity_main.xml
Labels: bug, da!
